# Generated by Django 3.0.2 on 2020-01-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
