# Generated by Django 3.0.2 on 2020-02-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20200204_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='application_video'),
        ),
    ]
