# Generated by Django 3.0.2 on 2020-02-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfile',
            name='name',
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='source',
            field=models.FileField(blank=True, null=True, upload_to='project_source'),
        ),
    ]
