# Generated by Django 3.0.2 on 2020-02-07 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200207_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditedVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('video', models.FileField(upload_to='edited_video')),
                ('thumbnail', models.ImageField(upload_to='edited_video_thumbnail')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edited_videos', to='projects.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
