# Generated by Django 3.0.2 on 2020-02-10 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
