# Generated by Django 3.0.2 on 2020-02-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
