# Generated by Django 3.0.2 on 2020-02-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='editedvideo',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
