# Generated by Django 3.0.2 on 2020-02-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_editedvideo_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editedvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='edited_video_thumbnail'),
        ),
    ]
