# Generated by Django 3.0.2 on 2020-02-04 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='confirmed',
        ),
    ]
