# Generated by Django 3.0.2 on 2020-02-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0003_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='has_answer',
            field=models.BooleanField(default=False),
        ),
    ]
