# Generated by Django 3.0.2 on 2020-02-04 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20200204_0634'),
        ('suggestions', '0004_suggestion_has_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suggestion', to='applications.Application'),
        ),
    ]
