# Generated by Django 3.0.2 on 2020-01-21 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('caption', models.CharField(max_length=80)),
                ('video', models.FileField(upload_to='')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='notices.Notice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
