# Generated by Django 3.0.2 on 2020-02-11 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0004_auto_20200130_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticevideo',
            name='caption',
        ),
    ]
