# Generated by Django 3.0.2 on 2020-02-11 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0005_remove_noticevideo_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticevideo',
            name='notice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='notices.Notice'),
        ),
    ]
