# Generated by Django 3.0.2 on 2020-02-11 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0006_auto_20200211_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='name',
        ),
    ]
